# Generated by Django 5.2.9 on 2025-12-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo_number', models.CharField(help_text='IMO number (unique identifier)', max_length=10, unique=True)),
                ('vessel_name', models.CharField(db_index=True, max_length=200)),
                ('vessel_type', models.CharField(choices=[('VLCC', 'Very Large Crude Carrier (VLCC)'), ('SUEZMAX', 'Suezmax Tanker'), ('AFRAMAX', 'Aframax Tanker'), ('PANAMAX', 'Panamax Tanker'), ('MR', 'Medium Range Tanker'), ('LR1', 'Long Range 1 Tanker'), ('LR2', 'Long Range 2 Tanker'), ('HANDYSIZE', 'Handysize Tanker'), ('OTHER', 'Other')], max_length=20)),
                ('built_year', models.IntegerField(help_text='Year vessel was built')),
                ('flag', models.CharField(blank=True, max_length=50)),
                ('deadweight', models.DecimalField(decimal_places=2, help_text='Deadweight tonnage (DWT)', max_digits=10)),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, help_text='Gross tonnage (GT)', max_digits=10, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('engine_power', models.DecimalField(blank=True, decimal_places=2, help_text='Engine power in kW', max_digits=10, null=True)),
                ('cargo_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo capacity in cubic meters', max_digits=10, null=True)),
                ('charter_type', models.CharField(choices=[('SPOT', 'Spot Charter'), ('TIME_CHARTER', 'Time Charter'), ('BAREBOAT', 'Bareboat Charter')], default='SPOT', help_text='Type of charter', max_length=20)),
                ('is_tc_fleet', models.BooleanField(default=False, help_text='Is this vessel part of Time Charter fleet?')),
                ('charter_start_date', models.DateField(blank=True, help_text='Start date of time charter (if applicable)', null=True)),
                ('charter_end_date', models.DateField(blank=True, help_text='End date of time charter (if applicable)', null=True)),
                ('daily_hire_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily hire rate in USD (for TC fleet)', max_digits=10, null=True)),
                ('tc_charterer', models.CharField(blank=True, help_text='Charterer name (for TC fleet)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is vessel currently active?')),
                ('notes', models.TextField(blank=True)),
                ('external_db_id', models.CharField(blank=True, help_text='ID from external TC fleet database', max_length=100)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last sync from external database', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vessel_name'],
                'indexes': [models.Index(fields=['imo_number'], name='ships_ship_imo_num_d1857c_idx'), models.Index(fields=['vessel_name'], name='ships_ship_vessel__bcf720_idx'), models.Index(fields=['vessel_type'], name='ships_ship_vessel__1647bc_idx'), models.Index(fields=['is_active'], name='ships_ship_is_acti_16edfb_idx'), models.Index(fields=['is_tc_fleet'], name='ships_ship_is_tc_f_12a3b3_idx'), models.Index(fields=['charter_type'], name='ships_ship_charter_054e9f_idx'), models.Index(fields=['is_tc_fleet', 'charter_end_date'], name='ships_ship_is_tc_f_1e04c0_idx'), models.Index(fields=['is_active', 'vessel_name'], name='ships_ship_is_acti_8f0cca_idx')],
            },
        ),
    ]
