# Generated by Django 5.2.9 on 2025-12-29 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TCFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(db_index=True, help_text='Ship name at the time of this contract', max_length=200)),
                ('imo_number', models.CharField(db_index=True, help_text='IMO number (unique ship identifier, permanent)', max_length=10)),
                ('ship_type', models.CharField(choices=[('AFRAMAX', 'Aframax'), ('SUEZMAX', 'Suezmax'), ('VLCC', 'VLCC'), ('PANAMAX', 'Panamax'), ('MR', 'Mid Range'), ('LR1', 'Long Range 1'), ('LR2', 'Long Range 2'), ('HANDYSIZE', 'Handysize'), ('CHEMICAL', 'Chemical Tanker'), ('PRODUCT', 'Product Tanker'), ('OTHER', 'Other')], help_text='Type of vessel', max_length=20)),
                ('delivery_status', models.CharField(choices=[('INCOMING_TC', 'Incoming TC'), ('ON_TC', 'On TC'), ('REDELIVERED', 'Redelivered')], db_index=True, default='ON_TC', help_text='Current delivery status', max_length=20)),
                ('trade', models.CharField(choices=[('CRUDE', 'Crude'), ('PRODUCTS', 'Products'), ('CHEMICAL', 'Chemical'), ('MIXED', 'Mixed')], help_text='Type of trade', max_length=20)),
                ('owner_name', models.CharField(help_text='Ship owner name', max_length=200)),
                ('owner_email', models.EmailField(blank=True, help_text='Ship owner contact email', max_length=254)),
                ('technical_manager', models.CharField(blank=True, help_text='Technical manager name', max_length=200)),
                ('technical_manager_email', models.EmailField(blank=True, help_text='Technical manager contact email', max_length=254)),
                ('charter_length_years', models.DecimalField(decimal_places=2, help_text='Charter length in years (e.g., 1.5, 3.0)', max_digits=5)),
                ('tc_rate_monthly', models.DecimalField(decimal_places=2, help_text='Time charter rate per month in USD', max_digits=12)),
                ('radar_deal_number', models.CharField(db_index=True, help_text='RADAR deal number (e.g., A1234567) - must be unique', max_length=20, unique=True)),
                ('delivery_date', models.DateField(help_text='Actual or expected delivery date')),
                ('redelivery_date', models.DateField(help_text='Actual or expected redelivery date')),
                ('tcp_date', models.DateField(help_text='Time Charter Party contract date')),
                ('broker_name', models.CharField(blank=True, help_text='Broker name', max_length=200)),
                ('broker_email', models.EmailField(blank=True, help_text='Broker contact email', max_length=254)),
                ('broker_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Broker commission in percent (e.g., 1.5, 2.5)', max_digits=5, null=True)),
                ('delivery_location', models.CharField(blank=True, help_text='Delivery port/location', max_length=200)),
                ('redelivery_location', models.CharField(blank=True, help_text='Redelivery port/location', max_length=200)),
                ('bunkers_policy', models.CharField(blank=True, choices=[('CHARTERER', 'Charterer Account'), ('OWNER', 'Owner Account'), ('SHARED', 'Shared')], help_text='Bunkers policy', max_length=20)),
                ('summer_dwt', models.DecimalField(decimal_places=2, help_text='Summer deadweight tonnage', max_digits=10)),
                ('built_year', models.IntegerField(help_text='Year vessel was built')),
                ('flag', models.CharField(help_text='Vessel flag', max_length=50)),
                ('next_drydock_date', models.DateField(blank=True, help_text='Next scheduled dry-dock date', null=True)),
                ('trader_name', models.CharField(blank=True, help_text='Freight trader name (from your company)', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tc_fleet_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TC Fleet Contract',
                'verbose_name_plural': 'TC Fleet Contracts',
                'ordering': ['-delivery_date', 'ship_name'],
                'indexes': [models.Index(fields=['imo_number'], name='ships_tcfle_imo_num_fa851e_idx'), models.Index(fields=['ship_name'], name='ships_tcfle_ship_na_6484ea_idx'), models.Index(fields=['delivery_status'], name='ships_tcfle_deliver_1c3dc1_idx'), models.Index(fields=['radar_deal_number'], name='ships_tcfle_radar_d_e11fe5_idx'), models.Index(fields=['delivery_date'], name='ships_tcfle_deliver_19d0e9_idx'), models.Index(fields=['redelivery_date'], name='ships_tcfle_redeliv_81f909_idx'), models.Index(fields=['ship_type'], name='ships_tcfle_ship_ty_1685e2_idx'), models.Index(fields=['trade'], name='ships_tcfle_trade_6c6139_idx'), models.Index(fields=['owner_name'], name='ships_tcfle_owner_n_29c7e2_idx'), models.Index(fields=['trader_name'], name='ships_tcfle_trader__652804_idx'), models.Index(fields=['delivery_status', 'delivery_date'], name='ships_tcfle_deliver_7f3d0e_idx'), models.Index(fields=['imo_number', 'delivery_date'], name='ships_tcfle_imo_num_477dc8_idx')],
            },
        ),
    ]
