# Generated by Django 5.2.9 on 2025-12-23 11:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Owner code from RADAR', max_length=50, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('READ', 'Read Only'), ('READ_EXPORT', 'Read + Export'), ('WRITE', 'Write'), ('ADMIN', 'Administrator')], default='READ', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'claims_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('radar_claim_id', models.CharField(blank=True, help_text='Unique ID from RADAR', max_length=100, null=True, unique=True)),
                ('claim_type', models.CharField(choices=[('DEMURRAGE', 'Demurrage'), ('POST_DEAL', 'Post-Deal'), ('DESPATCH', 'Despatch'), ('DEAD_FREIGHT', 'Dead Freight'), ('OTHER', 'Other')], max_length=20)),
                ('cost_type', models.CharField(blank=True, choices=[('PORT_COSTS', 'Port Costs'), ('CANAL_COSTS', 'Canal Costs'), ('BUNKER_COSTS', 'Bunker Costs'), ('AGENCY_FEES', 'Agency Fees'), ('DEMURRAGE', 'Demurrage'), ('DESPATCH', 'Despatch'), ('OTHER', 'Other')], help_text='Specific cost type for post-deal claims', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('SUBMITTED', 'Submitted'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('payment_status', models.CharField(choices=[('NOT_SENT', 'Not Sent'), ('SENT', 'Sent to Owner'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Fully Paid'), ('TIMEBAR', 'Time-barred'), ('DISPUTED', 'Disputed')], default='NOT_SENT', max_length=20)),
                ('laytime_used', models.DecimalField(blank=True, decimal_places=2, help_text='Actual laytime used in days (for demurrage claims)', max_digits=10, null=True)),
                ('demurrage_days', models.DecimalField(decimal_places=2, default=0, help_text='Calculated demurrage days', max_digits=10)),
                ('claim_amount', models.DecimalField(decimal_places=2, help_text='Total claim amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid by owner', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('claim_deadline', models.DateField(blank=True, help_text='Contractual deadline to submit claim', null=True)),
                ('is_time_barred', models.BooleanField(default=False, help_text='Claim missed contractual deadline')),
                ('time_bar_date', models.DateField(blank=True, help_text='Date when claim became time-barred', null=True)),
                ('description', models.TextField(blank=True)),
                ('settlement_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes from RADAR or analysts')),
                ('last_radar_sync', models.DateTimeField(blank=True, null=True)),
                ('radar_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_owner_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_claims', to=settings.AUTH_USER_MODEL)),
                ('ship_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.shipowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='claims.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('CHARTER_PARTY', 'Charter Party'), ('SOF', 'Statement of Facts'), ('LAYTIME_CALC', 'Laytime Calculation'), ('CORRESPONDENCE', 'Correspondence'), ('INVOICE', 'Invoice'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.claim')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radar_voyage_id', models.CharField(help_text='Unique ID from RADAR', max_length=100, unique=True)),
                ('voyage_number', models.CharField(max_length=100)),
                ('vessel_name', models.CharField(max_length=200)),
                ('imo_number', models.CharField(blank=True, max_length=20)),
                ('charter_party', models.CharField(max_length=100)),
                ('load_port', models.CharField(max_length=100)),
                ('discharge_port', models.CharField(max_length=100)),
                ('laycan_start', models.DateField(help_text='Laycan start date')),
                ('laycan_end', models.DateField(help_text='Laycan end date')),
                ('demurrage_rate', models.DecimalField(decimal_places=2, help_text='Demurrage rate per day', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('laytime_allowed', models.DecimalField(decimal_places=2, help_text='Allowed laytime in days', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('assignment_status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed')], default='UNASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('last_radar_sync', models.DateTimeField(auto_now=True)),
                ('radar_data', models.JSONField(blank=True, default=dict, help_text='Raw data from RADAR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['WRITE', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_voyages', to=settings.AUTH_USER_MODEL)),
                ('ship_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='claims.shipowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.voyage'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['radar_voyage_id'], name='claims_voya_radar_v_71707e_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['assignment_status'], name='claims_voya_assignm_7f5c27_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['assigned_analyst'], name='claims_voya_assigne_144047_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_clai_claim_n_0cfa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['radar_claim_id'], name='claims_clai_radar_c_64a050_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['payment_status'], name='claims_clai_payment_16f09e_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['voyage'], name='claims_clai_voyage__434334_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['ship_owner'], name='claims_clai_ship_ow_c9d5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_to'], name='claims_clai_assigne_e70630_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['is_time_barred'], name='claims_clai_is_time_541990_idx'),
        ),
    ]
