# Generated by Django 5.2.9 on 2025-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_user_bio_user_created_by_user_dark_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READ', 'Read Only'), ('READ_EXPORT', 'Read + Export'), ('WRITE', 'Write'), ('TEAM_LEAD', 'Team Lead'), ('ADMIN', 'Administrator')], default='READ', max_length=20),
        ),
    ]
