# Generated by Django 5.2.9 on 2025-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
    ]
