# Generated by Django 5.2.9 on 2025-12-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_user_directory', 'Can view user directory'), ('export_users', 'Can export users to Excel')]},
        ),
    ]
