# Generated by Django 5.2.9 on 2025-12-27 22:38

from django.db import migrations


def grant_user_permissions_to_staff(apps, schema_editor):
    """Grant user directory permissions to all staff and admin users"""
    User = apps.get_model('claims', 'User')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get the User content type
    try:
        user_content_type = ContentType.objects.get(app_label='claims', model='user')
    except ContentType.DoesNotExist:
        # If content type doesn't exist yet, skip this migration
        return

    # Get or create the permissions
    view_perm, _ = Permission.objects.get_or_create(
        codename='view_user_directory',
        content_type=user_content_type,
        defaults={'name': 'Can view user directory'}
    )

    export_perm, _ = Permission.objects.get_or_create(
        codename='export_users',
        content_type=user_content_type,
        defaults={'name': 'Can export users to Excel'}
    )

    # Grant permissions to all staff users
    staff_users = User.objects.filter(is_staff=True)
    for user in staff_users:
        user.user_permissions.add(view_perm, export_perm)

    # Grant permissions to all ADMIN role users
    admin_users = User.objects.filter(role='ADMIN')
    for user in admin_users:
        user.user_permissions.add(view_perm, export_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RunPython(grant_user_permissions_to_staff, migrations.RunPython.noop),
    ]
