# Generated by Django 5.2.9 on 2025-12-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_grant_admin_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='version',
            field=models.IntegerField(default=0, help_text='Version number for optimistic locking'),
        ),
        migrations.CreateModel(
            name='VoyageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, help_text='When this assignment ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Current active assignment')),
                ('reassignment_reason', models.TextField(blank=True, help_text='Reason for reassignment (if applicable)')),
                ('assigned_by', models.ForeignKey(help_text='Team lead or user who made the assignment', on_delete=django.db.models.deletion.PROTECT, related_name='voyage_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(help_text='Analyst assigned to this voyage', on_delete=django.db.models.deletion.PROTECT, related_name='voyage_assignments', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='claims.voyage')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['voyage', 'is_active'], name='claims_voya_voyage__fc3c78_idx'), models.Index(fields=['assigned_to', 'is_active'], name='claims_voya_assigne_b28102_idx'), models.Index(fields=['assigned_at'], name='claims_voya_assigne_76d389_idx')],
            },
        ),
    ]
