# Generated by Django 5.2.9 on 2025-12-28 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_voyage_version_voyageassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(help_text='Claim number for reference (in case claim is deleted)', max_length=50)),
                ('action', models.CharField(choices=[('CREATED', 'Claim Created'), ('STATUS_CHANGED', 'Status Changed'), ('PAYMENT_STATUS_CHANGED', 'Payment Status Changed'), ('AMOUNT_CHANGED', 'Claim Amount Changed'), ('PAID_AMOUNT_CHANGED', 'Paid Amount Changed'), ('ASSIGNED', 'Claim Assigned'), ('REASSIGNED', 'Claim Reassigned'), ('DEADLINE_CHANGED', 'Deadline Changed'), ('TIME_BARRED', 'Marked Time-Barred'), ('DELETED', 'Claim Deleted')], max_length=50)),
                ('message', models.TextField(help_text='Description of what changed')),
                ('old_value', models.TextField(blank=True, help_text='Previous value (if applicable)')),
                ('new_value', models.TextField(blank=True, help_text='New value (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(help_text='The claim this activity is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='claims.claim')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', 'created_at'], name='claims_clai_claim_i_7754c6_idx'), models.Index(fields=['user', 'created_at'], name='claims_clai_user_id_0749a3_idx'), models.Index(fields=['action', 'created_at'], name='claims_clai_action_5a55a3_idx')],
            },
        ),
    ]
