# Generated by Django 5.2.9 on 2025-12-28 22:33

import claims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_claimactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=claims.models.claim_document_path),
        ),
    ]
