# Generated by Django 5.2.9 on 2025-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_document_cloud_storage_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['created_at'], name='claims_clai_created_d933ce_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['created_by'], name='claims_clai_created_9f4981_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_deadline'], name='claims_clai_claim_d_b33780_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_to', 'status'], name='claims_clai_assigne_de0801_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['ship_owner', 'payment_status'], name='claims_clai_ship_ow_bd6bab_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'created_at'], name='claims_clai_status_58edc3_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['is_time_barred', 'payment_status'], name='claims_clai_is_time_0f0a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['voyage', 'status'], name='claims_clai_voyage__337b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['claim', 'created_at'], name='claims_comm_claim_i_bd48e1_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='claims_comm_user_id_2bd584_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['claim', 'uploaded_at'], name='claims_docu_claim_i_8b92db_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='claims_docu_documen_5c0e01_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='claims_docu_uploade_5363b5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipowner',
            index=models.Index(fields=['name'], name='claims_ship_name_7d6d54_idx'),
        ),
        migrations.AddIndex(
            model_name='shipowner',
            index=models.Index(fields=['code'], name='claims_ship_code_77bf68_idx'),
        ),
        migrations.AddIndex(
            model_name='shipowner',
            index=models.Index(fields=['is_active'], name='claims_ship_is_acti_0306ba_idx'),
        ),
        migrations.AddIndex(
            model_name='shipowner',
            index=models.Index(fields=['is_active', 'name'], name='claims_ship_is_acti_d7afb2_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['ship_owner'], name='claims_voya_ship_ow_89a9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['voyage_number'], name='claims_voya_voyage__df24b3_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['vessel_name'], name='claims_voya_vessel__78fc12_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['created_at'], name='claims_voya_created_9ae07a_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['laycan_start'], name='claims_voya_laycan__8da916_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['ship_owner', 'assignment_status'], name='claims_voya_ship_ow_9b177c_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['assigned_analyst', 'assignment_status'], name='claims_voya_assigne_6555a8_idx'),
        ),
        migrations.AddIndex(
            model_name='voyage',
            index=models.Index(fields=['assignment_status', 'created_at'], name='claims_voya_assignm_fa8e96_idx'),
        ),
    ]
