# Generated by Django 5.2.9 on 2025-12-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='charter_type',
            field=models.CharField(choices=[('SPOT', 'Spot - 3rd Party Ship'), ('TRADED', 'Traded - Time Charter Ship')], default='SPOT', help_text='SPOT = 3rd party ship, TRADED = Time Charter ship', max_length=10),
        ),
    ]
