# Generated by Django 5.2.9 on 2026-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0011_voyage_charter_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=True, help_text="User must change password on first login"
            ),
        ),
    ]
