# Generated by Django 5.2.9 on 2025-12-28 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0010_performance_indexes'),
        ('ships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LOADING', 'Loading Operations'), ('DISCHARGING', 'Discharging Operations'), ('OFFHIRE', 'Off-hire Period'), ('DRYDOCK', 'Dry-docking'), ('STS', 'Ship-to-Ship Transfer'), ('BUNKERING', 'Bunkering'), ('WAITING', 'Waiting Time'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_port', models.CharField(blank=True, help_text='Loading port name (for loading/discharging activities)', max_length=200)),
                ('discharge_port', models.CharField(blank=True, help_text='Discharge port name (for loading/discharging activities)', max_length=200)),
                ('port_name', models.CharField(help_text='Port where activity takes place', max_length=200)),
                ('start_datetime', models.DateTimeField(help_text='Activity start date/time')),
                ('start_date_status', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACTUAL', 'Actual')], default='ESTIMATED', help_text='Is start date estimated or actual?', max_length=10)),
                ('end_datetime', models.DateTimeField(help_text='Activity end date/time')),
                ('end_date_status', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('ACTUAL', 'Actual')], default='ESTIMATED', help_text='Is end date estimated or actual?', max_length=10)),
                ('duration', models.DurationField(editable=False, help_text='Auto-calculated duration (end - start)')),
                ('cargo_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo quantity (tons)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('radar_activity_id', models.CharField(blank=True, help_text='Activity ID from RADAR system', max_length=100)),
                ('last_radar_sync', models.DateTimeField(blank=True, help_text='Last sync from RADAR', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='port_activities.activitytype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(help_text='Ship performing this activity', on_delete=django.db.models.deletion.PROTECT, related_name='port_activities', to='ships.ship')),
                ('voyage', models.ForeignKey(blank=True, help_text='Related voyage (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_activities', to='claims.voyage')),
            ],
            options={
                'verbose_name_plural': 'Port Activities',
                'ordering': ['ship', 'start_datetime'],
                'indexes': [models.Index(fields=['ship', 'start_datetime'], name='port_activi_ship_id_4418ad_idx'), models.Index(fields=['voyage'], name='port_activi_voyage__4bcffa_idx'), models.Index(fields=['activity_type'], name='port_activi_activit_af185f_idx'), models.Index(fields=['start_datetime'], name='port_activi_start_d_46b44e_idx'), models.Index(fields=['start_date_status'], name='port_activi_start_d_1c2a2c_idx'), models.Index(fields=['end_date_status'], name='port_activi_end_dat_e1d72a_idx'), models.Index(fields=['ship', 'activity_type', 'start_datetime'], name='port_activi_ship_id_72fe29_idx'), models.Index(fields=['voyage', 'start_datetime'], name='port_activi_voyage__151b4f_idx'), models.Index(fields=['activity_type', 'start_datetime'], name='port_activi_activit_e7699b_idx')],
            },
        ),
    ]
