# Generated by Django 5.2.9 on 2025-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='code',
            field=models.CharField(default='general', help_text='Activity code (e.g., load, discharge, bunkering)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='color_class',
            field=models.CharField(blank=True, help_text='CSS color class for UI display', max_length=50),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Bootstrap icon class for UI display', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='category',
            field=models.CharField(choices=[('CARGO_OPS', 'Cargo Operations'), ('BALLASTING', 'Ballasting Operations'), ('CLEANING', 'Cleaning & Preparation'), ('BUNKERING', 'Bunkering & Supplies'), ('MAINTENANCE', 'Maintenance & Repairs'), ('OPERATIONAL', 'Operational Status'), ('ADMINISTRATIVE', 'Administrative & Compliance'), ('OFFHIRE', 'Off-hire Events'), ('TRANSIT', 'Transit & Navigation'), ('COMMERCIAL', 'Commercial Activities')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(help_text='Display name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['code'], name='port_activi_code_a6577e_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['category'], name='port_activi_categor_57249c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['is_active'], name='port_activi_is_acti_481206_idx'),
        ),
    ]
