# Generated by Django 5.2.9 on 2025-12-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_activities', '0002_activitytype_code_activitytype_color_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portactivity',
            name='user_comments',
            field=models.TextField(blank=True, help_text='User comments - only editable field'),
        ),
        migrations.AlterField(
            model_name='portactivity',
            name='notes',
            field=models.TextField(blank=True, help_text='System notes from RADAR (read-only)'),
        ),
    ]
